#!/bin/bash

#PBS -l ncpus=48
#PBS -l ngpus=4
#PBS -l mem=160GB
#PBS -l jobfs=10GB
#PBS -q gpuvolta
#PBS -P dx2
#PBS -N Anemoi_Tutorial_GPU
#PBS -l walltime=48:00:00
#PBS -l storage=gdata/ma14+gdata/dx2
#PBS -l wd


source /g/data/dx2/hc7988/venvs/home/548/hc7988/Projects/ECMWF/training/2026-ml-bom-training/bin/activate
cd /home/548/hc7988/Projects/ECMWF/training/2026-ml-bom-training/1-Anemoi

export ANEMOI_CONFIG_PATH=$PWD/configs-new/

anemoi-training train --config-name aifs_ens_minimal.yaml